// Especificação dos meridianos e pontos de acupuntura.
//
// Cada ponto tem a localização clássica (padrão OMS), indicações tradicionais da
// MTC e um posicionamento anatômico (`at`) no modelo 3D, sempre do lado DIREITO
// do paciente — o esquerdo é gerado espelhando. Rode `npm run build:acupoints`
// depois de editar este arquivo.
import {
  RIG, V, below, abd, at, front, back, side, armU, armUt, armF, legY, belowKnee,
  aboveAnkle, abovePatella, head, headAt, headLine, face, foot, footEdge, hand, HAND
} from './rig.mjs'

const ICS = RIG.ics
const cT = RIG.cunThigh

export const MERIDIANS = [
  // ── Pulmão ──────────────────────────────────────────────────────────────────
  {
    id: 'LU', name: 'Pulmão', color: '#6EB5FF', element: 'Metal', hours: '3h–5h',
    desc: 'Governa a respiração, a pele e a defesa do corpo. Emoção associada: tristeza.',
    points: [
      { id: 'LU1', name: 'Zhongfu', pt: 'Palácio Central', cat: 'Mu do Pulmão',
        loc: '1º espaço intercostal, 6 cun lateral à linha média, 1 cun abaixo de LU2',
        ind: 'Tosse, asma, opressão no peito, dor no ombro', at: front(-6.2, ICS[1]) },
      { id: 'LU2', name: 'Yunmen', pt: 'Porta das Nuvens',
        loc: 'Fossa infraclavicular, 6 cun lateral à linha média',
        ind: 'Tosse, falta de ar, dor no peito e no ombro', at: front(-6.2, 1.452) },
      { id: 'LU3', name: 'Tianfu', pt: 'Palácio Celeste',
        loc: 'Face anterolateral do braço, 3 cun abaixo da prega axilar',
        ind: 'Asma, sangramento nasal, dor no braço', at: armU(6, 30) },
      { id: 'LU5', name: 'Chize', pt: 'Pântano do Cotovelo', cat: 'He (mar) · Água',
        loc: 'Prega do cotovelo, lado radial do tendão do bíceps',
        ind: 'Tosse com catarro, asma, dor no cotovelo', at: armUt(0.97, 35) },
      { id: 'LU6', name: 'Kongzui', pt: 'Abertura Máxima', cat: 'Xi (acúmulo)',
        loc: '7 cun acima da prega do punho, na linha LU5–LU9',
        ind: 'Crise aguda de tosse ou asma, dor de garganta', at: armF(7, 2) },
      { id: 'LU7', name: 'Lieque', pt: 'Sequência Interrompida', cat: 'Luo · Mestre do Ren Mai',
        loc: '1,5 cun acima da prega do punho, sobre o processo estiloide do rádio',
        ind: 'Tosse, resfriado, dor de cabeça, rigidez da nuca', at: armF(1.5, -12) },
      { id: 'LU9', name: 'Taiyuan', pt: 'Grande Abismo', cat: 'Yuan (fonte) · Hui dos vasos',
        loc: 'Prega do punho, lado radial da artéria radial',
        ind: 'Tosse crônica, falta de ar, fraqueza, dor no punho', at: armF(0.1, -45) },
      { id: 'LU10', name: 'Yuji', pt: 'Borda do Peixe', cat: 'Ying (nascente) · Fogo',
        loc: 'Eminência tenar, no meio do 1º metacarpo, na junção da pele da palma',
        ind: 'Dor de garganta, rouquidão, tosse seca', at: hand(-0.045, 0.058, 'palma') },
      { id: 'LU11', name: 'Shaoshang', pt: 'Pequeno Mercador', cat: 'Jing (poço) · Madeira',
        loc: 'Lado radial do polegar, 0,1 cun do canto da unha',
        ind: 'Dor de garganta aguda, febre, desmaio', at: at([-0.624, 0.996, 0.004], [0, 0, 1], 'snap') }
    ],
    paths: [['LU1', 'LU2', { w: armUt(0.12, 25) }, 'LU3', 'LU5', 'LU6', 'LU7', 'LU9', 'LU10', 'LU11']]
  },

  // ── Intestino Grosso ────────────────────────────────────────────────────────
  {
    id: 'LI', name: 'Intestino Grosso', color: '#E3C16F', element: 'Metal', hours: '5h–7h',
    desc: 'Elimina o que não serve ao corpo; muito usado para dores da face e da cabeça.',
    points: [
      { id: 'LI1', name: 'Shangyang', pt: 'Yang do Mercador', cat: 'Jing (poço) · Metal',
        loc: 'Lado radial do indicador, 0,1 cun do canto da unha',
        ind: 'Dor de garganta, dor de dente, febre', at: at([-0.697, 0.981, -0.027], HAND.N, 'snap') },
      { id: 'LI4', name: 'Hegu', pt: 'Vale da União', cat: 'Yuan (fonte) · Comando da face',
        loc: 'Dorso da mão, entre o 1º e o 2º metacarpo, no meio do 2º metacarpo',
        ind: 'Dor de cabeça, dor de dente, rinite, dores em geral. Evitar na gestação',
        at: hand(-0.015, 0.040, 'dorso') },
      { id: 'LI5', name: 'Yangxi', pt: 'Riacho Yang', cat: 'Jing (rio) · Fogo',
        loc: 'Tabaqueira anatômica, lado radial do dorso do punho',
        ind: 'Dor no punho, dor de cabeça, dor de dente', at: armF(0.15, 40) },
      { id: 'LI10', name: 'Shousanli', pt: 'Três Distâncias do Braço',
        loc: '2 cun abaixo de LI11, na linha LI5–LI11',
        ind: 'Dor e fraqueza do braço, dor no ombro, digestão', at: armF(10, 70) },
      { id: 'LI11', name: 'Quchi', pt: 'Lagoa da Curva', cat: 'He (mar) · Terra',
        loc: 'Extremidade lateral da prega do cotovelo (cotovelo fletido)',
        ind: 'Febre, alergias e coceira de pele, pressão alta, dor no cotovelo', at: armF(12, 78) },
      { id: 'LI14', name: 'Binao', pt: 'Braço e Ombro',
        loc: 'Na inserção do deltoide, 7 cun acima de LI11',
        ind: 'Dor no ombro e no braço, problemas nos olhos', at: armU(7, 88) },
      { id: 'LI15', name: 'Jianyu', pt: 'Osso do Ombro',
        loc: 'Depressão anterior e inferior ao acrômio (braço abduzido)',
        ind: 'Dor e limitação do ombro, bursite', at: armUt(0.06, 62) },
      { id: 'LI18', name: 'Futu', pt: 'Apoio da Proeminência',
        loc: 'Lateral do pescoço, na altura do pomo de Adão, entre as porções do esternocleidomastóideo',
        ind: 'Tosse, rouquidão, dor de garganta', at: headAt(1.515, 72) },
      { id: 'LI20', name: 'Yingxiang', pt: 'Receber a Fragrância',
        loc: 'No sulco nasolabial, ao lado da asa do nariz',
        ind: 'Rinite, sinusite, nariz entupido, perda do olfato', at: face(-0.021, 1.600) }
    ],
    paths: [['LI1', 'LI4', 'LI5', 'LI10', 'LI11', 'LI14', 'LI15', { w: front(-5.6, 1.47, 0.8) }, 'LI18', { w: face(-0.035, 1.575, -0.3) }, 'LI20']]
  },

  // ── Estômago ────────────────────────────────────────────────────────────────
  {
    id: 'ST', name: 'Estômago', color: '#F4D03F', element: 'Terra', hours: '7h–9h',
    desc: 'Recebe e digere os alimentos; um dos meridianos mais usados para energia e digestão.',
    points: [
      { id: 'ST1', name: 'Chengqi', pt: 'Recipiente das Lágrimas',
        loc: 'Abaixo da pupila, entre o globo ocular e a borda infraorbital',
        ind: 'Olhos vermelhos, lacrimejamento, tique da pálpebra', at: face(-0.028, 1.630) },
      { id: 'ST2', name: 'Sibai', pt: 'Quatro Brancos',
        loc: 'Abaixo da pupila, no forame infraorbital',
        ind: 'Problemas oculares, sinusite, paralisia facial', at: face(-0.029, 1.617) },
      { id: 'ST4', name: 'Dicang', pt: 'Celeiro da Terra',
        loc: 'Lateral ao canto da boca',
        ind: 'Paralisia facial, salivação, nevralgia', at: face(-0.027, 1.573) },
      { id: 'ST6', name: 'Jiache', pt: 'Mandíbula',
        loc: 'No masseter, 1 dedo acima e à frente do ângulo da mandíbula',
        ind: 'Dor de dente, ATM, bruxismo, paralisia facial', at: headAt(1.565, 58) },
      { id: 'ST7', name: 'Xiaguan', pt: 'Abaixo da Articulação',
        loc: 'Depressão abaixo do arco zigomático, à frente da ATM (boca fechada)',
        ind: 'Dor na ATM, dor de dente, zumbido', at: headAt(1.617, 66) },
      { id: 'ST8', name: 'Touwei', pt: 'Canto da Cabeça',
        loc: '0,5 cun dentro da linha do cabelo no canto da testa, 4,5 cun lateral à linha média',
        ind: 'Dor de cabeça frontal, tontura, visão turva', at: head(52, 30) },
      { id: 'ST9', name: 'Renying', pt: 'Acolhida do Homem',
        loc: 'Altura do pomo de Adão, borda anterior do esternocleidomastóideo (sobre a carótida)',
        ind: 'Dor de garganta, pressão alta, falta de ar', at: headAt(1.512, 38) },
      { id: 'ST12', name: 'Quepen', pt: 'Bacia Vazia',
        loc: 'Centro da fossa supraclavicular, 4 cun lateral à linha média',
        ind: 'Tosse, asma, dor de garganta', at: front(-4, 1.468, 0.6) },
      { id: 'ST18', name: 'Rugen', pt: 'Raiz da Mama',
        loc: '5º espaço intercostal, na linha mamilar',
        ind: 'Mastite, pouco leite, tosse, dor no peito', at: front(-4, ICS[5]) },
      { id: 'ST21', name: 'Liangmen', pt: 'Portão do Grão',
        loc: '4 cun acima do umbigo, 2 cun lateral',
        ind: 'Dor de estômago, gastrite, náusea', at: front(-2, abd(4)) },
      { id: 'ST25', name: 'Tianshu', pt: 'Pivô Celeste', cat: 'Mu do Intestino Grosso',
        loc: '2 cun lateral ao umbigo',
        ind: 'Prisão de ventre, diarreia, distensão e dor abdominal', at: front(-2, abd(0)) },
      { id: 'ST28', name: 'Shuidao', pt: 'Caminho da Água',
        loc: '3 cun abaixo do umbigo, 2 cun lateral',
        ind: 'Retenção urinária, edema, cólica menstrual', at: front(-2, abd(-3)) },
      { id: 'ST29', name: 'Guilai', pt: 'Retorno',
        loc: '4 cun abaixo do umbigo, 2 cun lateral',
        ind: 'Cólica e irregularidade menstrual', at: front(-2, abd(-4)) },
      { id: 'ST30', name: 'Qichong', pt: 'Impulso do Qi',
        loc: '5 cun abaixo do umbigo, 2 cun lateral, na borda superior do púbis',
        ind: 'Dor inguinal, problemas reprodutivos', at: front(-2, abd(-5)) },
      { id: 'ST31', name: 'Biguan', pt: 'Portão da Coxa',
        loc: 'Abaixo da espinha ilíaca anterossuperior, na altura da prega glútea',
        ind: 'Dor e fraqueza na coxa e no quadril', at: legY(0.80, 22) },
      { id: 'ST32', name: 'Futu', pt: 'Coelho Deitado',
        loc: '6 cun acima da borda lateral superior da patela',
        ind: 'Dor e fraqueza da coxa e do joelho', at: abovePatella(6, 22) },
      { id: 'ST34', name: 'Liangqiu', pt: 'Monte da Viga', cat: 'Xi (acúmulo)',
        loc: '2 cun acima da borda lateral superior da patela',
        ind: 'Dor aguda de estômago, dor no joelho', at: abovePatella(2, 32) },
      { id: 'ST35', name: 'Dubi', pt: 'Nariz do Bezerro',
        loc: 'Olho lateral do joelho, abaixo da patela, lateral ao ligamento patelar',
        ind: 'Dor, inchaço e artrose do joelho', at: legY(0.487, 28) },
      { id: 'ST36', name: 'Zusanli', pt: 'Três Distâncias da Perna', cat: 'He (mar) · Comando do abdome',
        loc: '3 cun abaixo de ST35, um dedo lateral à crista da tíbia',
        ind: 'Cansaço, digestão, imunidade, dor no joelho — um dos pontos mais usados',
        at: belowKnee(3.3, 38) },
      { id: 'ST37', name: 'Shangjuxu', pt: 'Grande Vazio Superior', cat: 'He inferior do Intestino Grosso',
        loc: '6 cun abaixo de ST35',
        ind: 'Diarreia, prisão de ventre, dor abdominal', at: belowKnee(6.3, 38) },
      { id: 'ST38', name: 'Tiaokou', pt: 'Abertura Estreita',
        loc: '8 cun abaixo de ST35',
        ind: 'Ombro congelado (tratamento à distância), dor na perna', at: belowKnee(8.3, 38) },
      { id: 'ST39', name: 'Xiajuxu', pt: 'Grande Vazio Inferior', cat: 'He inferior do Intestino Delgado',
        loc: '9 cun abaixo de ST35',
        ind: 'Dor no baixo ventre, diarreia, dor lombar', at: belowKnee(9.3, 38) },
      { id: 'ST40', name: 'Fenglong', pt: 'Abundância', cat: 'Luo · Ponto da fleuma',
        loc: '8 cun abaixo de ST35, dois dedos lateral à crista da tíbia',
        ind: 'Catarro, tosse, tontura, sensação de peso', at: belowKnee(8.3, 62) },
      { id: 'ST41', name: 'Jiexi', pt: 'Riacho Liberado', cat: 'Jing (rio) · Fogo',
        loc: 'Centro da prega anterior do tornozelo, entre os tendões',
        ind: 'Dor no tornozelo, dor de cabeça frontal', at: at([-0.160, 0.072, -0.02], [0, 0.35, 1], 'out') },
      { id: 'ST42', name: 'Chongyang', pt: 'Impulso Yang', cat: 'Yuan (fonte)',
        loc: 'Ponto mais alto do dorso do pé, sobre a artéria dorsal do pé',
        ind: 'Dor no dorso do pé, falta de apetite', at: foot(-0.158, 0.035, 1, 0.03) },
      { id: 'ST43', name: 'Xiangu', pt: 'Vale Afundado', cat: 'Shu (riacho) · Madeira',
        loc: 'Entre o 2º e o 3º metatarso, proximal às articulações',
        ind: 'Edema, dor no dorso do pé', at: foot(-0.160, 0.090) },
      { id: 'ST44', name: 'Neiting', pt: 'Pátio Interno', cat: 'Ying (nascente) · Água',
        loc: 'Entre o 2º e o 3º dedo do pé, na borda da membrana',
        ind: 'Dor de dente, gengivite, febre', at: foot(-0.160, 0.128) },
      { id: 'ST45', name: 'Lidui', pt: 'Troca Rigorosa', cat: 'Jing (poço) · Metal',
        loc: 'Lado lateral do 2º dedo do pé, 0,1 cun do canto da unha',
        ind: 'Sono agitado, pesadelos, febre', at: foot(-0.156, 0.160) }
    ],
    paths: [
      ['ST1', 'ST2', 'ST4', { w: headAt(1.553, 42) }, 'ST6', 'ST7', { w: head(62, 22) }, 'ST8'],
      [{ w: headAt(1.553, 42) }, 'ST9', 'ST12', { w: front(-4, ICS[2]) }, 'ST18', { w: front(-2.2, abd(7)) }, 'ST21', 'ST25', 'ST28', 'ST29', 'ST30',
        'ST31', 'ST32', 'ST34', 'ST35', 'ST36', 'ST37', 'ST38', 'ST39', 'ST41', 'ST42', 'ST43', 'ST44', 'ST45']
    ]
  },

  // ── Baço-Pâncreas ───────────────────────────────────────────────────────────
  {
    id: 'SP', name: 'Baço-Pâncreas', color: '#E59866', element: 'Terra', hours: '9h–11h',
    desc: 'Transforma o alimento em energia e sustenta o sangue. Emoção associada: preocupação.',
    points: [
      { id: 'SP1', name: 'Yinbai', pt: 'Branco Oculto', cat: 'Jing (poço) · Madeira',
        loc: 'Lado medial do hálux, 0,1 cun do canto da unha',
        ind: 'Sangramento uterino, sonhos excessivos, distensão', at: footEdge(0.014, 0.150, 1) },
      { id: 'SP2', name: 'Dadu', pt: 'Grande Metrópole', cat: 'Ying (nascente) · Fogo',
        loc: 'Lado medial do hálux, distal à 1ª articulação metatarsofalângica',
        ind: 'Distensão abdominal, febre', at: footEdge(0.016, 0.128, 1) },
      { id: 'SP3', name: 'Taibai', pt: 'Branco Supremo', cat: 'Yuan (fonte) · Terra',
        loc: 'Borda medial do pé, proximal à cabeça do 1º metatarso',
        ind: 'Digestão fraca, cansaço, sensação de peso', at: footEdge(0.020, 0.095, 1) },
      { id: 'SP4', name: 'Gongsun', pt: 'Neto do Imperador', cat: 'Luo · Mestre do Chong Mai',
        loc: 'Borda medial do pé, distal à base do 1º metatarso',
        ind: 'Dor de estômago, vômito, diarreia, menstruação irregular', at: footEdge(0.022, 0.060, 1) },
      { id: 'SP5', name: 'Shangqiu', pt: 'Colina do Comércio', cat: 'Jing (rio) · Metal',
        loc: 'Depressão anteroinferior ao maléolo medial',
        ind: 'Dor no tornozelo, distensão abdominal', at: at([-0.150, 0.058, 0.000], [1, 0, 0.6], 'out') },
      { id: 'SP6', name: 'Sanyinjiao', pt: 'Encontro dos Três Yin', cat: 'Cruzamento Baço · Fígado · Rim',
        loc: '3 cun acima do maléolo medial, atrás da borda medial da tíbia',
        ind: 'Cólica e TPM, insônia, digestão, ansiedade. Evitar na gestação', at: aboveAnkle(3, -105) },
      { id: 'SP8', name: 'Diji', pt: 'Pivô da Terra', cat: 'Xi (acúmulo)',
        loc: '3 cun abaixo de SP9, atrás da borda medial da tíbia',
        ind: 'Cólica menstrual aguda, dor abdominal', at: belowKnee(4.4, -110) },
      { id: 'SP9', name: 'Yinlingquan', pt: 'Fonte do Monte Yin', cat: 'He (mar) · Água',
        loc: 'Depressão abaixo do côndilo medial da tíbia',
        ind: 'Retenção de líquidos, edema, dor no joelho', at: belowKnee(1.4, -110) },
      { id: 'SP10', name: 'Xuehai', pt: 'Mar do Sangue',
        loc: '2 cun acima da borda medial superior da patela, no vasto medial',
        ind: 'Menstruação irregular, coceira, eczema', at: abovePatella(2, -62) },
      { id: 'SP15', name: 'Daheng', pt: 'Grande Horizontal',
        loc: '4 cun lateral ao umbigo',
        ind: 'Prisão de ventre, diarreia, dor abdominal', at: front(-4, abd(0)) },
      { id: 'SP21', name: 'Dabao', pt: 'Grande Envoltório', cat: 'Grande Luo do Baço',
        loc: 'Linha axilar média, 6º espaço intercostal',
        ind: 'Dor no corpo todo, fraqueza nos membros, dor no tórax', at: side(1.235, 92) }
    ],
    paths: [['SP1', 'SP2', 'SP3', 'SP4', 'SP5', 'SP6', 'SP8', 'SP9', 'SP10', { w: legY(0.72, -55) },
      { w: front(-3.6, abd(-5.2)) }, 'SP15', { w: front(-4, abd(3.5)) }, { w: front(-6, ICS[5]) }, { w: front(-6, ICS[2]) }, 'SP21']]
  },

  // ── Coração ─────────────────────────────────────────────────────────────────
  {
    id: 'HT', name: 'Coração', color: '#FF5A5F', element: 'Fogo', hours: '11h–13h',
    desc: 'Abriga a mente (Shen); ligado ao sono, à memória e às emoções. Emoção: alegria.',
    points: [
      { id: 'HT1', name: 'Jiquan', pt: 'Fonte Suprema',
        loc: 'Centro da axila, sobre a artéria axilar',
        ind: 'Dor no peito e no braço, palpitação', at: at([-0.222, 1.30, -0.085], [0, -1, 0], 'near') },
      { id: 'HT3', name: 'Shaohai', pt: 'Pequeno Mar', cat: 'He (mar) · Água',
        loc: 'Extremidade medial da prega do cotovelo (cotovelo fletido)',
        ind: 'Dor no cotovelo, tremor, ansiedade', at: armUt(0.97, -75) },
      { id: 'HT5', name: 'Tongli', pt: 'Comunicação Interior', cat: 'Luo',
        loc: '1 cun acima da prega do punho, lado radial do tendão do flexor ulnar do carpo',
        ind: 'Palpitação, perda súbita da voz, ansiedade', at: armF(1, -128) },
      { id: 'HT6', name: 'Yinxi', pt: 'Fenda Yin', cat: 'Xi (acúmulo)',
        loc: '0,5 cun acima da prega do punho',
        ind: 'Suor noturno, palpitação, dor no peito', at: armF(0.5, -130) },
      { id: 'HT7', name: 'Shenmen', pt: 'Portão do Espírito', cat: 'Yuan (fonte) · Terra',
        loc: 'Prega do punho, lado radial do tendão do flexor ulnar do carpo',
        ind: 'Insônia, ansiedade, palpitação, memória — acalma a mente', at: armF(0.1, -132) },
      { id: 'HT8', name: 'Shaofu', pt: 'Pequena Mansão', cat: 'Ying (nascente) · Fogo',
        loc: 'Palma, entre o 4º e o 5º metacarpo, onde toca a ponta do dedo mínimo',
        ind: 'Palpitação, agitação, calor', at: hand(0.0, -0.036, 'palma') },
      { id: 'HT9', name: 'Shaochong', pt: 'Pequeno Impulso', cat: 'Jing (poço) · Madeira',
        loc: 'Lado radial do dedo mínimo, 0,1 cun do canto da unha',
        ind: 'Palpitação, febre, perda de consciência', at: at([-0.686, 1.001, -0.105], HAND.N, 'snap') }
    ],
    paths: [['HT1', { w: armU(5, -80) }, 'HT3', 'HT5', 'HT6', 'HT7', 'HT8', { w: at([-0.666, 1.021, -0.111], [0.705, -0.702, -0.104], 'snap') }, 'HT9']]
  },

  // ── Intestino Delgado ───────────────────────────────────────────────────────
  {
    id: 'SI', name: 'Intestino Delgado', color: '#F1948A', element: 'Fogo', hours: '13h–15h',
    desc: 'Separa o puro do impuro; muito usado para dores de pescoço, ombro e escápula.',
    points: [
      { id: 'SI1', name: 'Shaoze', pt: 'Pequeno Pântano', cat: 'Jing (poço) · Metal',
        loc: 'Lado ulnar do dedo mínimo, 0,1 cun do canto da unha',
        ind: 'Pouco leite materno, dor de cabeça, febre', at: at([-0.688, 1.001, -0.116], [0, 0, -1], 'snap') },
      { id: 'SI3', name: 'Houxi', pt: 'Riacho de Trás', cat: 'Shu (riacho) · Mestre do Du Mai',
        loc: 'Borda ulnar da mão, proximal à 5ª articulação metacarpofalângica',
        ind: 'Torcicolo, dor na nuca e nas costas, dor lombar aguda', at: hand(0.002, -0.046, 'ulnar') },
      { id: 'SI4', name: 'Wangu', pt: 'Osso do Punho', cat: 'Yuan (fonte)',
        loc: 'Borda ulnar da mão, entre a base do 5º metacarpo e o hamato',
        ind: 'Dor no punho e nos dedos, rigidez do pescoço', at: hand(-0.058, -0.040, 'ulnar') },
      { id: 'SI6', name: 'Yanglao', pt: 'Sustentar os Idosos', cat: 'Xi (acúmulo)',
        loc: '1 cun acima do punho, na depressão radial à cabeça da ulna',
        ind: 'Dor aguda nas costas e no ombro, visão turva', at: armF(1, 150) },
      { id: 'SI8', name: 'Xiaohai', pt: 'Pequeno Mar', cat: 'He (mar) · Terra',
        loc: 'Entre o olécrano e o epicôndilo medial do úmero',
        ind: 'Dor no cotovelo, no pescoço e no ombro', at: armUt(0.97, -150) },
      { id: 'SI9', name: 'Jianzhen', pt: 'Ombro Verdadeiro',
        loc: '1 cun acima da prega axilar posterior',
        ind: 'Dor no ombro e na escápula', at: armUt(0.14, 196) },
      { id: 'SI10', name: 'Naoshu', pt: 'Shu do Braço',
        loc: 'Acima de SI9, abaixo da espinha da escápula',
        ind: 'Dor e fraqueza do ombro', at: back(-7.6, 1.395) },
      { id: 'SI11', name: 'Tianzong', pt: 'Ancestral Celeste',
        loc: 'Centro da fossa infraespinal da escápula',
        ind: 'Dor na escápula e no ombro', at: back(-4.8, 1.350) },
      { id: 'SI12', name: 'Bingfeng', pt: 'Pegar o Vento',
        loc: 'Centro da fossa supraespinal, acima de SI11',
        ind: 'Dor no ombro, dificuldade para levantar o braço', at: back(-5, 1.442) },
      { id: 'SI18', name: 'Quanliao', pt: 'Fenda do Zigoma',
        loc: 'Abaixo do osso zigomático, na vertical do canto externo do olho',
        ind: 'Paralisia facial, dor de dente, tique facial', at: face(-0.046, 1.605, -0.45) },
      { id: 'SI19', name: 'Tinggong', pt: 'Palácio da Audição',
        loc: 'À frente do trago, na depressão que se forma ao abrir a boca',
        ind: 'Zumbido, perda auditiva, dor de ouvido, ATM', at: headAt(1.625, 80) }
    ],
    paths: [['SI1', 'SI3', 'SI4', 'SI6', 'SI8', 'SI9', 'SI10', 'SI11', 'SI12', { w: back(-2.6, 1.47) },
      { w: headAt(1.535, 88) }, { w: headAt(1.575, 68) }, 'SI18', 'SI19']]
  },

  // ── Bexiga ──────────────────────────────────────────────────────────────────
  {
    id: 'BL', name: 'Bexiga', color: '#3D7DDB', element: 'Água', hours: '15h–17h',
    desc: 'O meridiano mais longo: percorre as costas e tem os pontos Shu de todos os órgãos.',
    points: [
      { id: 'BL1', name: 'Jingming', pt: 'Olhos Brilhantes',
        loc: 'Ligeiramente acima do canto interno do olho',
        ind: 'Olhos secos, visão turva, cansaço visual', at: face(-0.014, 1.640) },
      { id: 'BL2', name: 'Zanzhu', pt: 'Bambu Reunido',
        loc: 'Extremidade medial da sobrancelha',
        ind: 'Dor de cabeça frontal, sinusite, cansaço visual', at: face(-0.016, 1.656) },
      { id: 'BL10', name: 'Tianzhu', pt: 'Pilar Celeste',
        loc: '1,3 cun lateral à linha média, na linha posterior do cabelo, borda lateral do trapézio',
        ind: 'Dor e rigidez da nuca, dor de cabeça occipital', at: back(-1.3, 1.590) },
      { id: 'BL11', name: 'Dazhu', pt: 'Grande Lançadeira', cat: 'Hui dos ossos',
        loc: '1,5 cun lateral à borda inferior do processo espinhoso de T1',
        ind: 'Dor nas costas e articulações, rigidez da nuca', at: back(-1.5, below('T1')) },
      { id: 'BL12', name: 'Fengmen', pt: 'Portão do Vento',
        loc: '1,5 cun lateral à borda inferior de T2',
        ind: 'Resfriado, gripe, tosse, rigidez da nuca', at: back(-1.5, below('T2')) },
      { id: 'BL13', name: 'Feishu', pt: 'Shu do Pulmão', cat: 'Shu dorsal do Pulmão',
        loc: '1,5 cun lateral à borda inferior de T3',
        ind: 'Tosse, asma, alergias respiratórias', at: back(-1.5, below('T3')) },
      { id: 'BL14', name: 'Jueyinshu', pt: 'Shu do Pericárdio', cat: 'Shu dorsal do Pericárdio',
        loc: '1,5 cun lateral à borda inferior de T4',
        ind: 'Palpitação, dor no peito, ansiedade', at: back(-1.5, below('T4')) },
      { id: 'BL15', name: 'Xinshu', pt: 'Shu do Coração', cat: 'Shu dorsal do Coração',
        loc: '1,5 cun lateral à borda inferior de T5',
        ind: 'Palpitação, insônia, ansiedade, memória', at: back(-1.5, below('T5')) },
      { id: 'BL17', name: 'Geshu', pt: 'Shu do Diafragma', cat: 'Hui do sangue',
        loc: '1,5 cun lateral à borda inferior de T7',
        ind: 'Soluço, anemia, eczema', at: back(-1.5, below('T7')) },
      { id: 'BL18', name: 'Ganshu', pt: 'Shu do Fígado', cat: 'Shu dorsal do Fígado',
        loc: '1,5 cun lateral à borda inferior de T9',
        ind: 'Irritabilidade, problemas oculares, dor no hipocôndrio', at: back(-1.5, below('T9')) },
      { id: 'BL19', name: 'Danshu', pt: 'Shu da Vesícula', cat: 'Shu dorsal da Vesícula Biliar',
        loc: '1,5 cun lateral à borda inferior de T10',
        ind: 'Gosto amargo, dor no hipocôndrio', at: back(-1.5, below('T10')) },
      { id: 'BL20', name: 'Pishu', pt: 'Shu do Baço', cat: 'Shu dorsal do Baço',
        loc: '1,5 cun lateral à borda inferior de T11',
        ind: 'Digestão fraca, cansaço, distensão', at: back(-1.5, below('T11')) },
      { id: 'BL21', name: 'Weishu', pt: 'Shu do Estômago', cat: 'Shu dorsal do Estômago',
        loc: '1,5 cun lateral à borda inferior de T12',
        ind: 'Dor de estômago, náusea, falta de apetite', at: back(-1.5, below('T12')) },
      { id: 'BL22', name: 'Sanjiaoshu', pt: 'Shu do Triplo Aquecedor', cat: 'Shu dorsal do Triplo Aquecedor',
        loc: '1,5 cun lateral à borda inferior de L1',
        ind: 'Edema, retenção de líquidos, distensão', at: back(-1.5, below('L1')) },
      { id: 'BL23', name: 'Shenshu', pt: 'Shu do Rim', cat: 'Shu dorsal do Rim',
        loc: '1,5 cun lateral à borda inferior de L2',
        ind: 'Dor lombar, cansaço, zumbido, problemas urinários', at: back(-1.5, below('L2')) },
      { id: 'BL25', name: 'Dachangshu', pt: 'Shu do Intestino Grosso', cat: 'Shu dorsal do Intestino Grosso',
        loc: '1,5 cun lateral à borda inferior de L4',
        ind: 'Dor lombar, ciática, prisão de ventre', at: back(-1.5, below('L4')) },
      { id: 'BL27', name: 'Xiaochangshu', pt: 'Shu do Intestino Delgado', cat: 'Shu dorsal do Intestino Delgado',
        loc: '1,5 cun lateral à linha média, na altura do 1º forame sacral',
        ind: 'Dor sacral, problemas urinários e intestinais', at: back(-1.5, V.S1) },
      { id: 'BL28', name: 'Pangguangshu', pt: 'Shu da Bexiga', cat: 'Shu dorsal da Bexiga',
        loc: '1,5 cun lateral à linha média, na altura do 2º forame sacral',
        ind: 'Retenção urinária, cistite, dor lombossacral', at: back(-1.5, V.S2) },
      { id: 'BL32', name: 'Ciliao', pt: 'Segundo Forame',
        loc: 'No 2º forame sacral',
        ind: 'Cólica menstrual, dor lombossacral, problemas urinários', at: back(-0.8, V.S2 - 0.006) },
      { id: 'BL36', name: 'Chengfu', pt: 'Sustentação',
        loc: 'Centro da prega glútea',
        ind: 'Dor lombar, ciática, hemorroidas', at: legY(0.808, 178) },
      { id: 'BL37', name: 'Yinmen', pt: 'Portão da Abundância',
        loc: '6 cun abaixo de BL36, na linha BL36–BL40',
        ind: 'Dor lombar, ciática, dor na coxa', at: legY(0.808 - 6 * cT, 178) },
      { id: 'BL40', name: 'Weizhong', pt: 'Centro da Curva', cat: 'He (mar) · Comando das costas',
        loc: 'Centro da prega poplítea (atrás do joelho)',
        ind: 'Dor lombar, ciática, dor no joelho', at: legY(0.497, 180) },
      { id: 'BL43', name: 'Gaohuang', pt: 'Região Vital',
        loc: '3 cun lateral à borda inferior de T4, na borda medial da escápula',
        ind: 'Cansaço profundo, tosse crônica', at: back(-3, below('T4')) },
      { id: 'BL52', name: 'Zhishi', pt: 'Morada da Vontade',
        loc: '3 cun lateral à borda inferior de L2',
        ind: 'Dor lombar, cansaço, problemas urinários', at: back(-3, below('L2')) },
      { id: 'BL54', name: 'Zhibian', pt: 'Extremo da Ordem',
        loc: '3 cun lateral ao hiato sacral, na altura do 4º forame sacral',
        ind: 'Ciática, dor lombossacral, hemorroidas', at: back(-3, V.S4) },
      { id: 'BL57', name: 'Chengshan', pt: 'Apoio da Montanha',
        loc: 'Abaixo dos ventres da panturrilha, 8 cun abaixo de BL40',
        ind: 'Cãibra na panturrilha, hemorroidas, dor lombar', at: belowKnee(8, 180) },
      { id: 'BL58', name: 'Feiyang', pt: 'Voar para Cima', cat: 'Luo',
        loc: '7 cun acima de BL60, lateral e inferior a BL57',
        ind: 'Dor lombar e nas pernas, fraqueza nas pernas', at: aboveAnkle(7, 150) },
      { id: 'BL60', name: 'Kunlun', pt: 'Montanhas Kunlun', cat: 'Jing (rio) · Fogo',
        loc: 'Entre o maléolo lateral e o tendão de Aquiles',
        ind: 'Dor lombar, dor de cabeça, torcicolo. Evitar na gestação', at: aboveAnkle(0, 132) },
      { id: 'BL62', name: 'Shenmai', pt: 'Vaso Estendido', cat: 'Mestre do Yang Qiao Mai',
        loc: 'Depressão logo abaixo do maléolo lateral',
        ind: 'Insônia, dor de cabeça, dor lombar, tontura', at: footEdge(0.042, -0.045, -1, -0.170) },
      { id: 'BL67', name: 'Zhiyin', pt: 'Alcance do Yin', cat: 'Jing (poço) · Metal',
        loc: 'Lado lateral do 5º dedo do pé, 0,1 cun do canto da unha',
        ind: 'Feto em posição pélvica (moxa), dor de cabeça', at: footEdge(0.012, 0.118, -1) }
    ],
    paths: [
      ['BL1', 'BL2', { w: headLine(-0.030, 40) }, { w: headLine(-0.030, 80) }, { w: headLine(-0.030, 125) },
        { w: headLine(-0.032, 160) }, 'BL10', 'BL11', 'BL12', 'BL13', 'BL14', 'BL15', 'BL17', 'BL18', 'BL19', 'BL20',
        'BL21', 'BL22', 'BL23', 'BL25', 'BL27', 'BL28', 'BL32', 'BL36', 'BL37', 'BL40', 'BL57', 'BL58', 'BL60', 'BL62', 'BL67'],
      [{ w: back(-3, below('T2')) }, 'BL43', { w: back(-3, below('T9')) }, 'BL52', 'BL54', { w: legY(0.75, 162) }, { w: legY(0.60, 170) }, 'BL40']
    ]
  },

  // ── Rim ─────────────────────────────────────────────────────────────────────
  {
    id: 'KI', name: 'Rim', color: '#8E7CF0', element: 'Água', hours: '17h–19h',
    desc: 'Guarda a energia vital (Jing); ligado aos ossos, ouvidos e à vitalidade. Emoção: medo.',
    points: [
      { id: 'KI1', name: 'Yongquan', pt: 'Fonte Borbulhante', cat: 'Jing (poço) · Madeira',
        loc: 'Planta do pé, depressão do terço anterior (ao dobrar os dedos)',
        ind: 'Desmaio, pressão alta, insônia, agitação', at: foot(-0.160, 0.102, -1) },
      { id: 'KI2', name: 'Rangu', pt: 'Vale Ardente', cat: 'Ying (nascente) · Fogo',
        loc: 'Borda medial do pé, abaixo da tuberosidade do navicular',
        ind: 'Suor noturno, calor, garganta seca', at: footEdge(0.022, 0.035, 1) },
      { id: 'KI3', name: 'Taixi', pt: 'Grande Riacho', cat: 'Yuan (fonte) · Terra',
        loc: 'Entre o maléolo medial e o tendão de Aquiles',
        ind: 'Dor lombar, zumbido, cansaço, insônia — fortalece o Rim', at: aboveAnkle(0.2, -132) },
      { id: 'KI6', name: 'Zhaohai', pt: 'Mar Brilhante', cat: 'Mestre do Yin Qiao Mai',
        loc: '1 cun abaixo do maléolo medial',
        ind: 'Insônia, garganta seca, menstruação irregular', at: at([-0.160, 0.046, -0.038], [1, 0, 0], 'out') },
      { id: 'KI7', name: 'Fuliu', pt: 'Corrente de Retorno', cat: 'Jing (rio) · Metal',
        loc: '2 cun acima de KI3, à frente do tendão de Aquiles',
        ind: 'Edema, suor espontâneo ou noturno, dor lombar', at: aboveAnkle(2.2, -140) },
      { id: 'KI10', name: 'Yingu', pt: 'Vale Yin', cat: 'He (mar) · Água',
        loc: 'Extremidade medial da prega poplítea, entre os tendões',
        ind: 'Dor no joelho, problemas urinários', at: legY(0.497, -152) },
      { id: 'KI16', name: 'Huangshu', pt: 'Shu das Membranas',
        loc: '0,5 cun lateral ao umbigo',
        ind: 'Prisão de ventre, dor e distensão abdominal', at: front(-0.6, abd(0)) },
      { id: 'KI27', name: 'Shufu', pt: 'Mansão Shu',
        loc: 'Abaixo da clavícula, 2 cun lateral à linha média',
        ind: 'Tosse, asma, dor no peito', at: front(-2, 1.452) }
    ],
    paths: [['KI1', 'KI2', { w: at([-0.150, 0.050, -0.055], [1, 0, -0.3], 'out') }, 'KI6', 'KI3', 'KI7', { w: belowKnee(5, -130) }, 'KI10',
      { w: legY(0.70, -140) }, { w: front(-0.6, abd(-5)) }, 'KI16', { w: front(-0.6, abd(6)) }, { w: front(-2, ICS[5]) }, { w: front(-2, ICS[2]) }, 'KI27']]
  },

  // ── Pericárdio ──────────────────────────────────────────────────────────────
  {
    id: 'PC', name: 'Pericárdio', color: '#E84393', element: 'Fogo', hours: '19h–21h',
    desc: 'Protege o Coração; muito usado para ansiedade, náusea e aperto no peito.',
    points: [
      { id: 'PC1', name: 'Tianchi', pt: 'Lago Celeste',
        loc: '4º espaço intercostal, 1 cun lateral ao mamilo',
        ind: 'Dor no peito, tosse, mastite', at: front(-5, ICS[4]) },
      { id: 'PC3', name: 'Quze', pt: 'Pântano da Curva', cat: 'He (mar) · Água',
        loc: 'Prega do cotovelo, lado ulnar do tendão do bíceps',
        ind: 'Dor no cotovelo, palpitação, náusea', at: armUt(0.97, -18) },
      { id: 'PC4', name: 'Ximen', pt: 'Portão da Fenda', cat: 'Xi (acúmulo)',
        loc: '5 cun acima da prega do punho, entre os tendões',
        ind: 'Dor aguda no peito, palpitação', at: armF(5, -60) },
      { id: 'PC5', name: 'Jianshi', pt: 'Mensageiro', cat: 'Jing (rio) · Metal',
        loc: '3 cun acima da prega do punho, entre os tendões',
        ind: 'Palpitação, náusea, ansiedade', at: armF(3, -72) },
      { id: 'PC6', name: 'Neiguan', pt: 'Passagem Interna', cat: 'Luo · Mestre do Yin Wei Mai',
        loc: '2 cun acima da prega do punho, entre os tendões do palmar longo e do flexor radial do carpo',
        ind: 'Náusea e enjoo, ansiedade, palpitação, aperto no peito', at: armF(2, -80) },
      { id: 'PC7', name: 'Daling', pt: 'Grande Colina', cat: 'Yuan (fonte) · Terra',
        loc: 'Centro da prega do punho, entre os tendões',
        ind: 'Ansiedade, insônia, túnel do carpo', at: armF(0.1, -90) },
      { id: 'PC8', name: 'Laogong', pt: 'Palácio do Trabalho', cat: 'Ying (nascente) · Fogo',
        loc: 'Centro da palma, entre o 2º e o 3º metacarpo',
        ind: 'Agitação, calor, aftas', at: hand(0.0, 0.012, 'palma') },
      { id: 'PC9', name: 'Zhongchong', pt: 'Impulso Central', cat: 'Jing (poço) · Madeira',
        loc: 'Ponta do dedo médio',
        ind: 'Desmaio, febre alta, insolação', at: at([-0.712, 0.973, -0.056], HAND.F, 'snap') }
    ],
    paths: [['PC1', { w: armU(8, -30) }, { w: armU(4, -22) }, 'PC3', 'PC4', 'PC5', 'PC6', 'PC7', 'PC8', 'PC9']]
  },

  // ── Triplo Aquecedor ────────────────────────────────────────────────────────
  {
    id: 'TE', name: 'Triplo Aquecedor', color: '#FF9F43', element: 'Fogo', hours: '21h–23h',
    desc: 'Coordena a circulação de água e energia entre as três partes do tronco.',
    points: [
      { id: 'TE1', name: 'Guanchong', pt: 'Impulso do Portão', cat: 'Jing (poço) · Metal',
        loc: 'Lado ulnar do dedo anelar, 0,1 cun do canto da unha',
        ind: 'Febre, dor de garganta, dor de cabeça', at: at([-0.708, 0.982, -0.093], HAND.N, 'snap') },
      { id: 'TE3', name: 'Zhongzhu', pt: 'Ilhota Central', cat: 'Shu (riacho) · Madeira',
        loc: 'Dorso da mão, entre o 4º e o 5º metacarpo, proximal às articulações',
        ind: 'Zumbido, dor de cabeça temporal, dor nos dedos', at: hand(0.0, -0.036, 'dorso') },
      { id: 'TE4', name: 'Yangchi', pt: 'Lago Yang', cat: 'Yuan (fonte)',
        loc: 'Centro da prega dorsal do punho',
        ind: 'Dor no punho, sede, cansaço', at: armF(0.1, 95) },
      { id: 'TE5', name: 'Waiguan', pt: 'Passagem Externa', cat: 'Luo · Mestre do Yang Wei Mai',
        loc: '2 cun acima da prega dorsal do punho, entre rádio e ulna',
        ind: 'Resfriado, dor de cabeça temporal, zumbido, dor no braço', at: armF(2, 100) },
      { id: 'TE6', name: 'Zhigou', pt: 'Vala do Ramo', cat: 'Jing (rio) · Fogo',
        loc: '3 cun acima da prega dorsal do punho, entre rádio e ulna',
        ind: 'Prisão de ventre, dor nas costelas', at: armF(3, 104) },
      { id: 'TE10', name: 'Tianjing', pt: 'Poço Celeste', cat: 'He (mar) · Terra',
        loc: '1 cun acima do olécrano, com o cotovelo fletido',
        ind: 'Dor no cotovelo, enxaqueca', at: armU(1.2, 172) },
      { id: 'TE14', name: 'Jianliao', pt: 'Fenda do Ombro',
        loc: 'Depressão posterior e inferior ao acrômio (braço abduzido)',
        ind: 'Dor no ombro, ombro congelado', at: armUt(0.06, 128) },
      { id: 'TE17', name: 'Yifeng', pt: 'Proteção do Vento',
        loc: 'Atrás do lóbulo da orelha, entre a mandíbula e o processo mastoide',
        ind: 'Zumbido, dor de ouvido, paralisia facial, ATM', at: headAt(1.598, 102) },
      { id: 'TE21', name: 'Ermen', pt: 'Portão da Orelha',
        loc: 'À frente da incisura supratrágica (boca aberta)',
        ind: 'Zumbido, surdez, dor de ouvido', at: headAt(1.640, 80) },
      { id: 'TE23', name: 'Sizhukong', pt: 'Bambu de Seda',
        loc: 'Extremidade lateral da sobrancelha',
        ind: 'Dor de cabeça, enxaqueca, tique da pálpebra', at: face(-0.051, 1.657, -0.55) }
    ],
    paths: [['TE1', 'TE3', 'TE4', 'TE5', 'TE6', { w: armF(8, 130) }, 'TE10', { w: armU(5, 150) }, 'TE14',
      { w: back(-6, 1.462, 0.6) }, { w: headAt(1.555, 110) }, 'TE17', { w: headAt(1.635, 102) }, { w: headAt(1.662, 90) }, 'TE21', 'TE23']]
  },

  // ── Vesícula Biliar ─────────────────────────────────────────────────────────
  {
    id: 'GB', name: 'Vesícula Biliar', color: '#7BD389', element: 'Madeira', hours: '23h–1h',
    desc: 'Percorre a lateral do corpo; ligado às decisões, às articulações e à cabeça.',
    points: [
      { id: 'GB1', name: 'Tongziliao', pt: 'Fenda da Pupila',
        loc: '0,5 cun lateral ao canto externo do olho',
        ind: 'Dor de cabeça, olhos vermelhos, visão turva', at: face(-0.054, 1.640, -0.6) },
      { id: 'GB2', name: 'Tinghui', pt: 'Encontro da Audição',
        loc: 'À frente da incisura intertrágica, abaixo de SI19 (boca aberta)',
        ind: 'Zumbido, surdez, ATM', at: headAt(1.610, 79) },
      { id: 'GB8', name: 'Shuaigu', pt: 'Vale do Condutor',
        loc: '1,5 cun acima do ápice da orelha',
        ind: 'Enxaqueca, tontura, ressaca', at: head(92, 36) },
      { id: 'GB12', name: 'Wangu', pt: 'Osso Final',
        loc: 'Depressão atrás e abaixo do processo mastoide',
        ind: 'Dor de cabeça, insônia, rigidez da nuca', at: headAt(1.598, 122) },
      { id: 'GB14', name: 'Yangbai', pt: 'Branco Yang',
        loc: '1 cun acima do meio da sobrancelha, na linha da pupila',
        ind: 'Dor de cabeça frontal, paralisia facial', at: face(-0.030, 1.680) },
      { id: 'GB20', name: 'Fengchi', pt: 'Lago do Vento',
        loc: 'Abaixo do occipital, entre o esternocleidomastóideo e o trapézio',
        ind: 'Dor de cabeça, torcicolo, tontura, resfriado', at: back(-2, 1.600, 0.15) },
      { id: 'GB21', name: 'Jianjing', pt: 'Poço do Ombro',
        loc: 'Ponto mais alto do ombro, entre C7 e o acrômio',
        ind: 'Tensão no ombro e trapézio, dor no pescoço. Evitar na gestação',
        at: at([-0.125, 1.40, -0.07], [0, 1, 0], 'out') },
      { id: 'GB24', name: 'Riyue', pt: 'Sol e Lua', cat: 'Mu da Vesícula Biliar',
        loc: '7º espaço intercostal, na linha mamilar',
        ind: 'Dor no hipocôndrio, azia, náusea', at: front(-4, ICS[7]) },
      { id: 'GB25', name: 'Jingmen', pt: 'Portão da Capital', cat: 'Mu do Rim',
        loc: 'Extremidade livre da 12ª costela',
        ind: 'Dor lombar e no flanco, problemas urinários', at: side(1.10, 118) },
      { id: 'GB26', name: 'Daimai', pt: 'Vaso da Cintura',
        loc: 'Abaixo da extremidade livre da 11ª costela, na altura do umbigo',
        ind: 'Corrimento, menstruação irregular, dor na cintura', at: side(abd(0), 86) },
      { id: 'GB29', name: 'Juliao', pt: 'Morada Agachada',
        loc: 'Ponto médio entre a espinha ilíaca anterossuperior e o trocânter maior',
        ind: 'Dor no quadril, ciática', at: side(0.905, 88) },
      { id: 'GB30', name: 'Huantiao', pt: 'Salto Circular',
        loc: 'Nádega: 1/3 lateral da linha entre o trocânter maior e o hiato sacral',
        ind: 'Ciática, dor no quadril e na perna', at: at([-0.095, 0.875, -0.04], [-0.45, 0, -1], 'out') },
      { id: 'GB31', name: 'Fengshi', pt: 'Mercado do Vento',
        loc: 'Face lateral da coxa, 7 cun acima da prega poplítea',
        ind: 'Coceira, dor e dormência na coxa', at: legY(0.497 + 7 * cT, 90) },
      { id: 'GB34', name: 'Yanglingquan', pt: 'Fonte da Colina Yang', cat: 'He (mar) · Hui dos tendões',
        loc: 'Depressão anterior e inferior à cabeça da fíbula',
        ind: 'Dores musculares e tendíneas, dor no joelho, cãibras', at: belowKnee(2, 78) },
      { id: 'GB37', name: 'Guangming', pt: 'Brilho', cat: 'Luo',
        loc: '5 cun acima do maléolo lateral, na borda anterior da fíbula',
        ind: 'Problemas oculares, dor na perna', at: aboveAnkle(5, 82) },
      { id: 'GB39', name: 'Xuanzhong', pt: 'Sino Suspenso', cat: 'Hui da medula',
        loc: '3 cun acima do maléolo lateral, na borda anterior da fíbula',
        ind: 'Torcicolo, fraqueza nas pernas', at: aboveAnkle(3, 88) },
      { id: 'GB40', name: 'Qiuxu', pt: 'Monte de Ruínas', cat: 'Yuan (fonte)',
        loc: 'Depressão anteroinferior ao maléolo lateral',
        ind: 'Entorse e dor no tornozelo, dor no flanco', at: at([-0.175, 0.055, 0.0], [-1, 0, 0.55], 'out') },
      { id: 'GB41', name: 'Zulinqi', pt: 'Lágrimas do Pé', cat: 'Shu (riacho) · Mestre do Dai Mai',
        loc: 'Dorso do pé, entre o 4º e o 5º metatarso, proximal',
        ind: 'Enxaqueca, dor nos seios, TPM', at: foot(-0.190, 0.068, 1, 0.02) },
      { id: 'GB43', name: 'Xiaxi', pt: 'Riacho Estreito', cat: 'Ying (nascente) · Água',
        loc: 'Entre o 4º e o 5º dedo do pé, na borda da membrana',
        ind: 'Dor de cabeça temporal, zumbido, tontura', at: foot(-0.190, 0.112) },
      { id: 'GB44', name: 'Zuqiaoyin', pt: 'Portal Yin do Pé', cat: 'Jing (poço) · Metal',
        loc: 'Lado lateral do 4º dedo do pé, 0,1 cun do canto da unha',
        ind: 'Enxaqueca, olhos vermelhos, insônia', at: foot(-0.186, 0.140) }
    ],
    paths: [['GB1', 'GB2', { w: headAt(1.650, 74) }, { w: head(78, 24) }, { w: head(86, 30) }, 'GB8', { w: head(112, 24) }, { w: headAt(1.625, 116) },
      'GB12', { w: head(40, 30) }, 'GB14', { w: headLine(-0.052, 40) }, { w: headLine(-0.052, 90) }, { w: headLine(-0.050, 140) }, 'GB20', 'GB21',
      { w: front(-5, 1.445, 0.4) }, { w: front(-6.4, 1.37) }, { w: side(1.27, 88) }, 'GB24', 'GB25', 'GB26', { w: side(0.99, 58) }, 'GB29', 'GB30', { w: legY(0.75, 92) }, 'GB31', { w: abovePatella(1, 84) },
      'GB34', 'GB37', 'GB39', 'GB40', 'GB41', 'GB43', 'GB44']]
  },

  // ── Fígado ──────────────────────────────────────────────────────────────────
  {
    id: 'LR', name: 'Fígado', color: '#27AE60', element: 'Madeira', hours: '1h–3h',
    desc: 'Mantém o fluxo livre da energia; ligado ao estresse, aos tendões e aos olhos. Emoção: raiva.',
    points: [
      { id: 'LR1', name: 'Dadun', pt: 'Grande Sinceridade', cat: 'Jing (poço) · Madeira',
        loc: 'Lado lateral do hálux, 0,1 cun do canto da unha',
        ind: 'Sangramento uterino, hérnia', at: foot(-0.140, 0.150) },
      { id: 'LR2', name: 'Xingjian', pt: 'Caminho Intermediário', cat: 'Ying (nascente) · Fogo',
        loc: 'Entre o 1º e o 2º dedo do pé, na borda da membrana',
        ind: 'Irritação, dor de cabeça, olhos vermelhos, insônia', at: foot(-0.144, 0.128) },
      { id: 'LR3', name: 'Taichong', pt: 'Grande Impulso', cat: 'Yuan (fonte) · Terra',
        loc: 'Dorso do pé, entre o 1º e o 2º metatarso, na depressão distal à junção dos ossos',
        ind: 'Estresse, irritabilidade, dor de cabeça, TPM, cólicas', at: foot(-0.145, 0.072, 1, 0.02) },
      { id: 'LR4', name: 'Zhongfeng', pt: 'Selo Médio', cat: 'Jing (rio) · Metal',
        loc: 'À frente do maléolo medial, medial ao tendão do tibial anterior',
        ind: 'Dor genital, retenção urinária, dor no tornozelo', at: at([-0.148, 0.072, -0.015], [0.8, 0, 1], 'out') },
      { id: 'LR5', name: 'Ligou', pt: 'Canal da Carcoma', cat: 'Luo',
        loc: '5 cun acima do maléolo medial, no centro da face medial da tíbia',
        ind: 'Coceira genital, menstruação irregular', at: aboveAnkle(5, -78) },
      { id: 'LR8', name: 'Ququan', pt: 'Fonte da Curva', cat: 'He (mar) · Água',
        loc: 'Extremidade medial da prega poplítea, acima do tendão semitendinoso',
        ind: 'Dor no joelho, problemas urinários e genitais', at: legY(0.505, -125) },
      { id: 'LR13', name: 'Zhangmen', pt: 'Portão da Conclusão', cat: 'Mu do Baço · Hui dos órgãos Zang',
        loc: 'Extremidade livre da 11ª costela',
        ind: 'Distensão, digestão difícil, dor no flanco', at: side(1.135, 68) },
      { id: 'LR14', name: 'Qimen', pt: 'Portão do Ciclo', cat: 'Mu do Fígado',
        loc: '6º espaço intercostal, na linha mamilar',
        ind: 'Dor nas costelas, azia, soluço, estresse', at: front(-4, ICS[6]) }
    ],
    paths: [['LR1', 'LR2', 'LR3', 'LR4', { w: aboveAnkle(2.5, -80) }, 'LR5', { w: belowKnee(6, -95) }, 'LR8', { w: legY(0.70, -80) },
      { w: front(-2.6, abd(-5.4)) }, { w: front(-4.6, abd(-1)) }, 'LR13', 'LR14']]
  },

  // ── Vaso Concepção (Ren Mai) ────────────────────────────────────────────────
  {
    id: 'CV', name: 'Vaso Concepção', color: '#35D0D6', element: 'Ren Mai', hours: '—',
    desc: 'Linha média da frente do corpo; nutre o Yin e os órgãos reprodutores.',
    bilateral: false,
    points: [
      { id: 'CV2', name: 'Qugu', pt: 'Osso Curvo',
        loc: 'Borda superior da sínfise púbica',
        ind: 'Incontinência, cólica, problemas genitais', at: front(0, abd(-5)) },
      { id: 'CV3', name: 'Zhongji', pt: 'Polo Médio', cat: 'Mu da Bexiga',
        loc: '4 cun abaixo do umbigo',
        ind: 'Cistite, retenção urinária, menstruação irregular', at: front(0, abd(-4)) },
      { id: 'CV4', name: 'Guanyuan', pt: 'Portão da Origem', cat: 'Mu do Intestino Delgado',
        loc: '3 cun abaixo do umbigo',
        ind: 'Cansaço, fortalecimento geral, problemas urinários e reprodutivos', at: front(0, abd(-3)) },
      { id: 'CV6', name: 'Qihai', pt: 'Mar do Qi',
        loc: '1,5 cun abaixo do umbigo',
        ind: 'Fadiga, fraqueza, distensão — tonifica a energia', at: front(0, abd(-1.5)) },
      { id: 'CV8', name: 'Shenque', pt: 'Portão do Espírito',
        loc: 'Centro do umbigo (somente moxabustão)',
        ind: 'Diarreia crônica, frio no abdome', at: front(0, abd(0)) },
      { id: 'CV9', name: 'Shuifen', pt: 'Separação das Águas',
        loc: '1 cun acima do umbigo',
        ind: 'Edema, retenção de líquidos', at: front(0, abd(1)) },
      { id: 'CV10', name: 'Xiawan', pt: 'Estômago Inferior',
        loc: '2 cun acima do umbigo',
        ind: 'Má digestão, distensão, vômito', at: front(0, abd(2)) },
      { id: 'CV12', name: 'Zhongwan', pt: 'Estômago Médio', cat: 'Mu do Estômago · Hui dos órgãos Fu',
        loc: '4 cun acima do umbigo',
        ind: 'Dor de estômago, azia, náusea, digestão lenta', at: front(0, abd(4)) },
      { id: 'CV14', name: 'Juque', pt: 'Grande Portal', cat: 'Mu do Coração',
        loc: '6 cun acima do umbigo',
        ind: 'Palpitação, ansiedade, azia', at: front(0, abd(6)) },
      { id: 'CV17', name: 'Danzhong', pt: 'Centro do Peito', cat: 'Mu do Pericárdio · Hui do Qi',
        loc: 'Linha média do esterno, na altura do 4º espaço intercostal (entre os mamilos)',
        ind: 'Aperto no peito, ansiedade, falta de ar', at: front(0, ICS[4]) },
      { id: 'CV22', name: 'Tiantu', pt: 'Proeminência Celeste',
        loc: 'Centro da fúrcula esternal',
        ind: 'Tosse, asma, garganta irritada, rouquidão', at: front(0, 1.462, 0.35) },
      { id: 'CV23', name: 'Lianquan', pt: 'Fonte da Esquina',
        loc: 'Linha média do pescoço, acima do osso hioide',
        ind: 'Dificuldade de fala, salivação', at: at([0, 1.522, -0.01], [0, -0.35, 1], 'out') },
      { id: 'CV24', name: 'Chengjiang', pt: 'Recipiente do Fluido',
        loc: 'Centro do sulco mentolabial',
        ind: 'Paralisia facial, dor de dente, salivação', at: face(0, 1.556) }
    ],
    paths: [['CV2', 'CV3', 'CV4', 'CV6', 'CV8', 'CV9', 'CV10', 'CV12', 'CV14', 'CV17', 'CV22', 'CV23', 'CV24']]
  },

  // ── Vaso Governador (Du Mai) ────────────────────────────────────────────────
  {
    id: 'GV', name: 'Vaso Governador', color: '#B39DFF', element: 'Du Mai', hours: '—',
    desc: 'Linha média das costas e da cabeça; governa todo o Yang e a coluna.',
    bilateral: false,
    points: [
      { id: 'GV1', name: 'Changqiang', pt: 'Longa Força', cat: 'Luo',
        loc: 'Entre a ponta do cóccix e o ânus',
        ind: 'Hemorroidas, dor no cóccix', at: back(0, 0.905) },
      { id: 'GV3', name: 'Yaoyangguan', pt: 'Portão Yang Lombar',
        loc: 'Abaixo do processo espinhoso de L4',
        ind: 'Dor lombar, fraqueza nas pernas', at: back(0, below('L4')) },
      { id: 'GV4', name: 'Mingmen', pt: 'Portão da Vida',
        loc: 'Abaixo do processo espinhoso de L2',
        ind: 'Dor lombar crônica, frio, cansaço', at: back(0, below('L2')) },
      { id: 'GV9', name: 'Zhiyang', pt: 'Alcance do Yang',
        loc: 'Abaixo do processo espinhoso de T7',
        ind: 'Dor nas costas, tosse, digestão', at: back(0, below('T7')) },
      { id: 'GV11', name: 'Shendao', pt: 'Caminho do Espírito',
        loc: 'Abaixo do processo espinhoso de T5',
        ind: 'Ansiedade, palpitação, insônia', at: back(0, below('T5')) },
      { id: 'GV12', name: 'Shenzhu', pt: 'Pilar do Corpo',
        loc: 'Abaixo do processo espinhoso de T3',
        ind: 'Tosse, asma, fortalece o corpo', at: back(0, below('T3')) },
      { id: 'GV14', name: 'Dazhui', pt: 'Grande Vértebra',
        loc: 'Abaixo do processo espinhoso de C7',
        ind: 'Febre, resfriado, rigidez da nuca, imunidade', at: back(0, below('C7')) },
      { id: 'GV15', name: 'Yamen', pt: 'Portão da Mudez',
        loc: '0,5 cun dentro da linha posterior do cabelo',
        ind: 'Rigidez da nuca, dificuldade de fala', at: back(0, 1.592) },
      { id: 'GV16', name: 'Fengfu', pt: 'Palácio do Vento',
        loc: '1 cun dentro da linha posterior do cabelo, abaixo da protuberância occipital',
        ind: 'Dor de cabeça, tontura, rigidez da nuca', at: back(0, 1.608) },
      { id: 'GV20', name: 'Baihui', pt: 'Cem Reuniões',
        loc: 'Topo da cabeça, na linha que liga os ápices das orelhas',
        ind: 'Ansiedade, dor de cabeça, tontura, memória — eleva o ânimo', at: headLine(0, 92) },
      { id: 'GV23', name: 'Shangxing', pt: 'Estrela Superior',
        loc: '1 cun dentro da linha anterior do cabelo',
        ind: 'Rinite, sinusite, dor de cabeça frontal', at: headLine(0, 38) },
      { id: 'GV24', name: 'Shenting', pt: 'Pátio do Espírito',
        loc: '0,5 cun dentro da linha anterior do cabelo',
        ind: 'Ansiedade, insônia, dor de cabeça frontal', at: headLine(0, 33) },
      { id: 'GV26', name: 'Shuigou', pt: 'Sulco da Água',
        loc: 'No terço superior do filtro labial',
        ind: 'Desmaio (primeiros socorros), dor lombar aguda', at: face(0, 1.588) }
    ],
    paths: [['GV1', { w: back(0, V.S3) }, 'GV3', 'GV4', 'GV9', 'GV11', 'GV12', 'GV14', { w: back(0, 1.55) }, 'GV15', 'GV16',
      { w: headLine(0, 150) }, { w: headLine(0, 120) }, 'GV20', 'GV23', 'GV24', { w: face(0, 1.650) }, { w: face(0, 1.620) }, 'GV26']]
  },

  // ── Pontos extras ───────────────────────────────────────────────────────────
  {
    id: 'EX', name: 'Pontos Extras', color: '#E8E8F0', element: 'Extra', hours: '—',
    desc: 'Pontos fora dos 14 meridianos, com ação específica e muito usados na clínica.',
    points: [
      { id: 'Yintang', code: 'EX-HN3', name: 'Yintang', pt: 'Salão da Impressão',
        loc: 'Ponto médio entre as sobrancelhas',
        ind: 'Ansiedade, insônia, rinite, dor de cabeça frontal — acalma', at: face(0, 1.652) },
      { id: 'Taiyang', code: 'EX-HN5', name: 'Taiyang', pt: 'Sol',
        loc: 'Têmpora, 1 cun atrás do ponto médio entre o fim da sobrancelha e o canto externo do olho',
        ind: 'Enxaqueca, dor de cabeça, olhos cansados', at: headAt(1.648, 56) },
      { id: 'Anmian', code: 'EX', name: 'Anmian', pt: 'Sono Tranquilo',
        loc: 'Atrás da orelha, entre TE17 e GB20',
        ind: 'Insônia, tontura, agitação', at: headAt(1.600, 128) },
      { id: 'Dingchuan', code: 'EX-B1', name: 'Dingchuan', pt: 'Acalmar a Asma',
        loc: '0,5 cun lateral a GV14 (abaixo de C7)',
        ind: 'Asma, tosse, rigidez da nuca', at: back(-0.5, below('C7')) },
      { id: 'Jianqian', code: 'EX-UE12', name: 'Jianqian', pt: 'Frente do Ombro',
        loc: 'Ponto médio entre a prega axilar anterior e LI15',
        ind: 'Dor no ombro, ombro congelado', at: armUt(0.12, 12) },
      { id: 'Luozhen', code: 'EX-UE8', name: 'Luozhen', pt: 'Travesseiro Caído',
        loc: 'Dorso da mão, entre o 2º e o 3º metacarpo, 0,5 cun proximal às articulações',
        ind: 'Torcicolo agudo, dor no pescoço', at: hand(0.018, 0.012, 'dorso') },
      { id: 'Zigong', code: 'EX-CA1', name: 'Zigong', pt: 'Útero',
        loc: '4 cun abaixo do umbigo, 3 cun lateral à linha média',
        ind: 'Cólica, menstruação irregular, fertilidade', at: front(-3, abd(-4)) },
      { id: 'Xiyan', code: 'EX-LE5', name: 'Xiyan', pt: 'Olho do Joelho',
        loc: 'Olho medial do joelho, abaixo da patela, medial ao ligamento patelar',
        ind: 'Dor e artrose do joelho', at: legY(0.487, -28) },
      { id: 'Dannang', code: 'EX-LE6', name: 'Dannang', pt: 'Vesícula',
        loc: '1 a 2 cun abaixo de GB34',
        ind: 'Cólica biliar, dor no hipocôndrio', at: belowKnee(3.5, 80) },
      { id: 'Lanwei', code: 'EX-LE7', name: 'Lanwei', pt: 'Apêndice',
        loc: '2 cun abaixo de ST36',
        ind: 'Dor abdominal, indigestão', at: belowKnee(5.3, 40) },
      { id: 'Shiqizhui', code: 'EX-B8', name: 'Shiqizhui', pt: '17ª Vértebra',
        loc: 'Abaixo do processo espinhoso de L5',
        ind: 'Dor lombar e sacral, cólica menstrual, ciática', at: back(0, below('L5')) },
      { id: 'Yaoyan', code: 'EX-B7', name: 'Yaoyan', pt: 'Olhos da Lombar',
        loc: '3,5 cun lateral à borda inferior de L4',
        ind: 'Dor e fraqueza lombar', at: back(-3.5, below('L4')) }
    ],
    paths: []
  }
]

// Protocolos prontos (pontos-base; bilaterais entram dos dois lados)
export const PROTOCOLS = [
  { id: 'lombar',    name: 'Dor lombar',             points: ['BL23', 'BL25', 'BL40', 'GV4', 'BL60', 'Yaoyan'] },
  { id: 'ciatica',   name: 'Ciática',                points: ['GB30', 'BL36', 'BL40', 'GB34', 'BL57', 'BL60'] },
  { id: 'cervical',  name: 'Pescoço / torcicolo',    points: ['GB20', 'GB21', 'BL10', 'SI3', 'GV14', 'Luozhen', 'GB39'] },
  { id: 'ombro',     name: 'Dor no ombro',           points: ['LI15', 'TE14', 'SI9', 'SI11', 'Jianqian', 'ST38'] },
  { id: 'joelho',    name: 'Dor no joelho',          points: ['ST35', 'Xiyan', 'ST36', 'SP9', 'GB34', 'BL40'] },
  { id: 'cefaleia',  name: 'Dor de cabeça',          points: ['GB20', 'LI4', 'Taiyang', 'Yintang', 'LR3', 'GV20'] },
  { id: 'enxaqueca', name: 'Enxaqueca',              points: ['GB20', 'Taiyang', 'TE5', 'GB41', 'LR3', 'GB8'] },
  { id: 'ansiedade', name: 'Ansiedade e estresse',   points: ['Yintang', 'HT7', 'PC6', 'GV20', 'LR3', 'CV17'] },
  { id: 'insonia',   name: 'Insônia',                points: ['HT7', 'SP6', 'Anmian', 'Yintang', 'KI6', 'BL62'] },
  { id: 'digestao',  name: 'Náusea e digestão',      points: ['PC6', 'ST36', 'CV12', 'SP4', 'ST25'] },
  { id: 'energia',   name: 'Fadiga / imunidade',     points: ['ST36', 'SP6', 'CV6', 'CV4', 'LI11', 'KI3'] },
  { id: 'colica',    name: 'Cólica menstrual / TPM', points: ['SP6', 'SP8', 'CV4', 'LR3', 'SP10', 'Zigong'] },
  { id: 'rinite',    name: 'Rinite / sinusite',      points: ['LI20', 'Yintang', 'LI4', 'BL2', 'GV23', 'LU7'] },
  { id: 'portoes',   name: 'Quatro Portões',         points: ['LI4', 'LR3'] }
]
